### ISSUE TITLE
Fix annoying warnings

### ISSUE THREAD

**Issue by cdcseacave** [boostorg/sort#37]
Conversion from int64 to int in header file `boost\sort\pdqsort\pdqsort.hpp`, reported as warning per few screen and for almost every CPP in my project:
- line 130
```
                limit += (int)(cur - sift);
```
- line 265
```
        int unknown_left = (int)(last - first) - ((num_r || num_l) ? block_size : 0);
```
And in file `boost\iostreams\filter\zstd.hpp`:
- line 94
```
    int error() const { return (int)error_; }
```

**Comment by spreadsort** [comment]
I've asked orsonpeters@gmail.com (the author) to follow up on this.

**Comment by spreadsort** [comment]
I've merged Orson's fix.
