### ISSUE TITLE
fatal error: 'boost/type_traits.hpp' file not found

### ISSUE THREAD

**Issue by Co1lin** [boostorg/sort#59]
Hi! I want to test these sorting algorithms, and I find that the readme says it is a include only lib. However, after `#include "boost/sort/sort.hpp"` in this repo, I got an error:

```
path/sort/include/boost/sort/spreadsort/spreadsort.hpp:26:10: fatal error: 'boost/type_traits.hpp' file not found
#include <boost/type_traits.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by spreadsort** [comment]
On Thu, Mar 24, 2022 at 6:25 AM Colin ***@***.***> wrote:

> Hi! I want to test these sorting algorithms, and I find that the readme
> says it is a include only lib. However, after #include
> "boost/sort/sort.hpp" in this repo, I got an error:
>
> path/sort/include/boost/sort/spreadsort/spreadsort.hpp:26:10: fatal error: 'boost/type_traits.hpp' file not found
> #include <boost/type_traits.hpp>
>          ^~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
>
> Hi Colin,

You need to download the entire boost repo (not just sort), and put it in
your path, and then it should work.  What we meant is you shouldn't have to
compile anything as long as you downloaded the boost source.  Boost likes
to have the sublibraries depend on boost includes where possible, which is
why it works that way.

**Comment by Co1lin** [comment]
Thanks!
