### ISSUE TITLE
boost/sort/common/util/insert.hpp #includes itself

### ISSUE THREAD

**Issue by urnathan** [boostorg/sort#64]
working on clang modules (as a proxy for C++20 header-units), I see that boost/sort/common/util/insert.hpp #includes itself.  That seems unnatural.

[boost-includes.txt](https://github.com/boostorg/sort/files/9447177/boost-includes.txt)

**Comment by nigels-com** [comment]
Resolved via PR #78, can be closed now.

**Comment by fjtapia** [comment]
The insert sort algorithm is in the file insert_sort.hpp.
This file has an include insert.hpp, which contains quick insert functions
in an ordered vector. DOES NOT INCLUDE HIMSELF

These functions were initially part of the insert_sort algorithm. But they
were later implemented in the insert sort.hpp file, so right now both the
include and the insert.hpp files are unnecessary.
The file test_insert_sort.cpp also tested those functions, and they part
were deleted from the file

They are remains of an old implementation, which I forgot to clean when I
uploaded the files to the repository, as well as a function placed between
comments in the file.
I had modified insert_sort.hpp, delete insert.hpp, and modified, too,
test_insert_sort

By the way, what program did you use to detect this?
Thanks

Francisco

**Comment by urnathan** [comment]
> By the way, what program did you use to detect this?

I probably hacked the compiler to avoid its header-macro optimization and then ran some python of the preprocessed output.  FWIW I've been wondering about the usefulness of a compiler warning for this kind of thing.
