### ISSUE TITLE
Document usage of pdqsort

### ISSUE THREAD

**Issue by mglisse** [boostorg/sort#68]
In the documentation of pdqsort, I have trouble finding essential information for its use:
1. what header do I need to include?
2. what namespace is the function in?

I can guess that 1. is either `boost/sort/sort.hpp` or `boost/sort/pdqsort/pdqsort.hpp`, but I don't know if the second one is official and guaranteed not to move. I can also find the namespace in the source code (or just guess), but it would be nice if this information was more prominently advertised in the documentation.

**Comment by spreadsort** [comment]
We have no intention of moving pdqsort.hpp.  Anything outside detail is considered part of the API.
If you have a suggestion on how to improve our documentation, I'd welcome a pull request.

**Comment by mglisse** [comment]
Thank you for the clarification about the API.

I don't know how to generate the documentation for boost, and don't have much time to learn.
A first idea would be to let doxygen run on pdqsort.hpp, for instance by mentioning pdqsort next to spreadsort in doc/Jamfile.v2 (and doc/doxygen/sort_doxyfile.txt and doc/sort.idx?) and regenerating the doc. That might be enough to turn `pdqsort` into a link to a page that has the information I want.
Otherwise, pdqsort.qbk's Usage section could say "Thus you can simply replace a call to __std_sort with boost::sort::pdqsort, available from <boost/sort/pdqsort/pdqsort.hpp>" (with the appropriate quickbook syntax) instead of the current `__pdqsort` which looks like a broken funcref for the moment.

introduction.qbk could also mention "These algorithms do not use any other library or utility, you only need to include <boost/sort/sort.hpp> or one of the more specific headers."

**Comment by spreadsort** [comment]
I apparently don't have the ability to regenerate the docs though mingw, which is how I'm currently updating Boost.  I retired my linux box a while back.  My employer is very clear that I'm not to work on Boost at work.
I believe everything inside the doxygen folder is autogenerated by doxygen when someone runs it, so I can skip that one file.

One update:
https://github.com/boostorg/sort/commit/641c2f02b5febbf1ad51f38d0a96afd8968bd5d0

The other:
https://github.com/boostorg/sort/commit/6df06af708ed619d3320b5e990c6c896e20a2aa6

I hope that resolves your concern.

**Comment by mglisse** [comment]
Thank you.
