### ISSUE TITLE
spreadsort support for wider integers (e.g., (unsigned) __int128)

### ISSUE THREAD

**Issue by thompsonbry** [boostorg/sort#69]
Hello, I am curious whether spreadsort is known to (or thought to) work with wider integer types using an appropriately written rightshift() method.

**Comment by thompsonbry** [comment]
Update: seems to work :-)

**Comment by spreadsort** [comment]
Yes.  It's important that the return type from rightshift be able to hold
the full potential range of numbers and be subtracted from another of its
type (basically act like an int of sufficient size).  As long as you've got
that and a comparison operator it should work fine.

Note that if your number is truly huge you might want to use string_sort to
avoid creating a huge data type on the stack every time you do a
"rightshift":
https://www.boost.org/doc/libs/1_81_0/libs/sort/doc/html/sort/single_thread/spreadsort/sort_hpp/string_sort.html,
but I'd be surprised if that did as well as integer_sort for something as
small as 128 bits.
Your rightshift functor should also be very cheap just like a comparison
operator.

**Comment by spreadsort** [comment]
On Wed, Feb 8, 2023 at 7:38 PM Steven Ross ***@***.***> wrote:

> Yes.  It's important that the return type from rightshift be able to hold
> the full potential range of numbers and be subtracted from another of its
> type (basically act like an int of sufficient size).  As long as you've got
> that and a comparison operator it should work fine.
>

It'll fail to compile if the number is larger than boost::uintmax_t, in
which case you'd have to use string_sort as noted below. There may be
platforms on which 128 bits is bigger than boost::uintmax_t.
